---
version: "3.9"

services:

  devopsdb:
    image: ashraysambu/sam:db

    ports:
      - "1111:3306"

    networks:
      - my-net

    deploy:
      replicas: 1

  application:
    image: ashraysambu/sam:app

    ports:
      - "1234:8080"

    networks:
      - my-net
      

    depends_on:
      - devopsdb

   

    deploy:
      replicas: 3

networks:

  my-net:
    driver: overlay

  


